
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMENT_END COMMENT_START DO DOT DOTSTRING ELSE EMIT FUNC_END FUNC_START ID IF LOOP NUMBER STRING THEN VARIABLEComandos : Comandos ComandoComandos : Comando : ExpressaoComando : ImprimeComando : CommentExpressao : Expressao Termo '+'Expressao : Expressao Termo '-'Expressao : Expressao Termo '*'Expressao : Expressao Termo '/'Expressao : Expressao Termo '%'Expressao : TermoImprime : Expressao DOTImprime : DOTSTRINGTermo : NUMBERComment : COMMENT_START Comandos COMMENT_END"
    
_lr_action_items = {'DOTSTRING':([0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,],[-2,7,-1,-3,-4,-5,-11,-13,-2,-14,-12,7,-6,-7,-8,-9,-10,-15,]),'COMMENT_START':([0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,],[-2,8,-1,-3,-4,-5,-11,-13,-2,-14,-12,8,-6,-7,-8,-9,-10,-15,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,],[-2,9,-1,9,-4,-5,-11,-13,-2,-14,-12,9,-6,-7,-8,-9,-10,-15,]),'$end':([0,1,2,3,4,5,6,7,9,11,13,14,15,16,17,18,],[-2,0,-1,-3,-4,-5,-11,-13,-14,-12,-6,-7,-8,-9,-10,-15,]),'COMMENT_END':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,],[-1,-3,-4,-5,-11,-13,-2,-14,-12,18,-6,-7,-8,-9,-10,-15,]),'DOT':([3,6,9,13,14,15,16,17,],[11,-11,-14,-6,-7,-8,-9,-10,]),'+':([9,10,],[-14,13,]),'-':([9,10,],[-14,14,]),'*':([9,10,],[-14,15,]),'/':([9,10,],[-14,16,]),'%':([9,10,],[-14,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comandos':([0,8,],[1,12,]),'Comando':([1,12,],[2,2,]),'Expressao':([1,12,],[3,3,]),'Imprime':([1,12,],[4,4,]),'Comment':([1,12,],[5,5,]),'Termo':([1,3,12,],[6,10,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comandos","S'",1,None,None,None),
  ('Comandos -> Comandos Comando','Comandos',2,'p_Comandos1','yacc.py',20),
  ('Comandos -> <empty>','Comandos',0,'p_Comandos2','yacc.py',24),
  ('Comando -> Expressao','Comando',1,'p_Comando1','yacc.py',28),
  ('Comando -> Imprime','Comando',1,'p_Comando2','yacc.py',32),
  ('Comando -> Comment','Comando',1,'p_Comando3','yacc.py',36),
  ('Expressao -> Expressao Termo +','Expressao',3,'p_Expressao1','yacc.py',40),
  ('Expressao -> Expressao Termo -','Expressao',3,'p_Expressao2','yacc.py',44),
  ('Expressao -> Expressao Termo *','Expressao',3,'p_Expressao3','yacc.py',48),
  ('Expressao -> Expressao Termo /','Expressao',3,'p_Expressao4','yacc.py',52),
  ('Expressao -> Expressao Termo %','Expressao',3,'p_Expressao5','yacc.py',56),
  ('Expressao -> Termo','Expressao',1,'p_Expressao6','yacc.py',60),
  ('Imprime -> Expressao DOT','Imprime',2,'p_Expressao_Print','yacc.py',64),
  ('Imprime -> DOTSTRING','Imprime',1,'p_Expressao_Print2','yacc.py',68),
  ('Termo -> NUMBER','Termo',1,'p_Termo1','yacc.py',72),
  ('Comment -> COMMENT_START Comandos COMMENT_END','Comment',3,'p_Comment','yacc.py',76),
]
