
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMENT_END COMMENT_START DO DOT ELSE EMIT FUNC_END FUNC_START ID IF LOOP NUMBER STRING THEN VARIABLEComandos : Comandos ExpressaoComandos : Comando : ExpressaoExpressao : Expressao Termo '+'Expressao : Expressao Termo '-'Expressao : Expressao Termo '*'Expressao : Expressao Termo '/'Expressao : Expressao Termo '%'Expressao : TermoTermo : NUMBERTermo : NUMBER DOT"
    
_lr_action_items = {'NUMBER':([0,1,2,3,4,6,7,8,9,10,11,],[-2,4,4,-9,-10,-11,-4,-5,-6,-7,-8,]),'$end':([0,1,2,3,4,6,7,8,9,10,11,],[-2,0,-1,-9,-10,-11,-4,-5,-6,-7,-8,]),'+':([4,5,6,],[-10,7,-11,]),'-':([4,5,6,],[-10,8,-11,]),'*':([4,5,6,],[-10,9,-11,]),'/':([4,5,6,],[-10,10,-11,]),'%':([4,5,6,],[-10,11,-11,]),'DOT':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comandos':([0,],[1,]),'Expressao':([1,],[2,]),'Termo':([1,2,],[3,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comandos","S'",1,None,None,None),
  ('Comandos -> Comandos Expressao','Comandos',2,'p_Comandos1','yacc.py',20),
  ('Comandos -> <empty>','Comandos',0,'p_Comandos2','yacc.py',24),
  ('Comando -> Expressao','Comando',1,'p_Comando1','yacc.py',28),
  ('Expressao -> Expressao Termo +','Expressao',3,'p_Expressao1','yacc.py',32),
  ('Expressao -> Expressao Termo -','Expressao',3,'p_Expressao2','yacc.py',36),
  ('Expressao -> Expressao Termo *','Expressao',3,'p_Expressao3','yacc.py',40),
  ('Expressao -> Expressao Termo /','Expressao',3,'p_Expressao4','yacc.py',44),
  ('Expressao -> Expressao Termo %','Expressao',3,'p_Expressao5','yacc.py',48),
  ('Expressao -> Termo','Expressao',1,'p_Expressao6','yacc.py',52),
  ('Termo -> NUMBER','Termo',1,'p_Termo1','yacc.py',56),
  ('Termo -> NUMBER DOT','Termo',2,'p_Termo2','yacc.py',60),
]
